name: Cypress-Tests

on: 
  workflow_dispatch:
  
jobs:
  cypress-electron-tests:  
    runs-on: ubuntu-latest
    container: 
      image: cypress/browsers:node-20.12.2-chrome-124.0.6367.155-1-ff-125.0.3-edge-124.0.2478.80-1
      options: --user 1001
    steps:
      - name: Get code 
        uses: actions/checkout@v4.1.5

      - name: Install dependencies
        run: yarn install

      - name: Run E2E tests
        run: node runner-electron.js
    env: 
      TARGET_TOKEN_ELECTRON: ${{ secrets.TARGET_TOKEN_ELECTRON}}

  cypress-chrome-tests:  
    needs: cypress-electron-tests
    runs-on: ubuntu-latest
    container: 
      image: cypress/browsers:node-20.12.2-chrome-124.0.6367.155-1-ff-125.0.3-edge-124.0.2478.80-1
      options: --user 1001
    steps:
      - name: Get code 
        uses: actions/checkout@v4.1.5

      - name: Install dependencies
        run: yarn install

      - name: Run E2E tests
        run: node runner-chrome.js
    env: 
      TARGET_TOKEN_CRHOME: ${{ secrets.TARGET_TOKEN_CRHOME}}
        
  cypress-firefox-tests:  
    needs: cypress-electron-tests
    runs-on: ubuntu-latest
    container: 
      image: cypress/browsers:node-20.12.2-chrome-124.0.6367.155-1-ff-125.0.3-edge-124.0.2478.80-1
      options: --user 1001
    steps:
      - name: Get code 
        uses: actions/checkout@v4.1.5

      - name: Install dependencies
        run: yarn install

      - name: Run E2E tests
        run: node runner-firefox.js
    env: 
      TARGET_TOKEN_FIREFOX: ${{ secrets.TARGET_TOKEN_FIREFOX}}
      
  cypress-edge-tests:  
    needs: cypress-electron-tests
    runs-on: ubuntu-latest
    container: 
      image: cypress/browsers:node-20.12.2-chrome-124.0.6367.155-1-ff-125.0.3-edge-124.0.2478.80-1
      options: --user 1001
    steps:
      - name: Get code 
        uses: actions/checkout@v4.1.5

      - name: Install dependencies
        run: yarn install

      - name: Run E2E tests
        run: node runner-edge.js
    env: 
      TARGET_TOKEN_EDGE: ${{ secrets.TARGET_TOKEN_EDGE}}

